# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170418_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
