# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-20 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20170420_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=b'', upload_to=b'teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
