# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-02 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default=b'', max_length=10, verbose_name='\u6807\u7b7e'),
        ),
    ]
