# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-03 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=b'', verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
